# Generated by Django 4.1 on 2022-10-08 14:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0002_vestidos_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='vestidos',
            name='autor',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='vestidos',
            name='fechaCarga',
            field=models.DateField(default=datetime.date(2022, 10, 8)),
        ),
        migrations.AlterField(
            model_name='vestidos',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='vestidos'),
        ),
    ]
