# Generated by Django 4.1 on 2022-10-08 14:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0003_vestidos_autor_vestidos_fechacarga_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vestidos',
            name='fechaCarga',
            field=models.DateField(default=datetime.datetime(2022, 10, 8, 14, 17, 35, 91453, tzinfo=datetime.timezone.utc)),
        ),
    ]
