# Generated by Django 4.1 on 2022-10-08 14:26

import datetime
import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0004_alter_vestidos_fechacarga'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vestidos',
            name='autor',
            field=models.CharField(default=django.contrib.auth.models.User, max_length=40),
        ),
        migrations.AlterField(
            model_name='vestidos',
            name='fechaCarga',
            field=models.DateField(default=datetime.datetime(2022, 10, 8, 14, 26, 23, 547537, tzinfo=datetime.timezone.utc)),
        ),
    ]
