# Generated by Django 4.1 on 2022-10-08 14:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0005_alter_vestidos_autor_alter_vestidos_fechacarga'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vestidos',
            name='autor',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='vestidos',
            name='fechaCarga',
            field=models.DateField(default=datetime.datetime(2022, 10, 8, 14, 29, 19, 870363, tzinfo=datetime.timezone.utc)),
        ),
    ]
